### ISSUE TITLE
How to remove (Not Secure) for the MERN?

### ISSUE THREAD

**Issue by melodydev0521** [melodydev0521/admin-berrygoodmedia#2]
Hello guys.
Now, I failed to deploy this project to vercel so I just created server in AWS EC2 instance.
In that, I built project to production and I can see that with IP Address.
But that is http so not secured.
How to manually make issue?

**Comment by LauJunMingX** [comment]
You need to use ngnix
Visit this site
https://beaglesecurity.com/blog/article/nginx-server-security.html

**Comment by melodydev0521** [comment]
Thanks junming
That works
